services:
  # Our PostgreSQL database
  db:
    # The docker image for postgres (we are using the latest image)
    image: postgres:latest
    # The ports to expose to the host container
    # 5432 (default postgres port)
    ports:
      - "5433:5432"
    # If we accidentally kill the running container, Docker Compose will restart it
    restart: always
    # Do not store plaintext passwords in source control lol
    environment:
      POSTGRES_PASSWORD: changemeinproduction!